import React, { useState } from 'react';
import { ArchiveItem } from '../types';
import { QrCode, Search, CheckCircle2, AlertCircle, ArrowRight, X, Sparkles, FileText, MapPin, Box } from 'lucide-react';

interface QrScannerModalProps {
  items: ArchiveItem[];
  onSelectFoundItem: (item: ArchiveItem) => void;
  onClose: () => void;
}

export const QrScannerModal: React.FC<QrScannerModalProps> = ({
  items,
  onSelectFoundItem,
  onClose,
}) => {
  const [scanInput, setScanInput] = useState('');
  const [matchedItem, setMatchedItem] = useState<ArchiveItem | null>(null);
  const [hasSearched, setHasSearched] = useState(false);

  const handleProcessScan = (codeValue: string) => {
    setHasSearched(true);
    let searchKey = codeValue.trim();

    // Try parsing as JSON if generated by system
    try {
      const parsed = JSON.parse(codeValue);
      if (parsed.id || parsed.noSurat) {
        searchKey = parsed.id || parsed.noSurat;
      }
    } catch (e) {
      // plain text fallback
    }

    const found = items.find(
      (i) =>
        i.id.toLowerCase() === searchKey.toLowerCase() ||
        i.nomorKeputusan.toLowerCase() === searchKey.toLowerCase() ||
        i.noDus.toLowerCase() === searchKey.toLowerCase()
    );

    setMatchedItem(found || null);
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-200">
      
      {/* Header Banner */}
      <div className="bg-slate-900 text-white p-6 rounded-2xl border border-slate-800 shadow-md flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <div className="inline-flex items-center gap-2 px-3 py-1 bg-blue-500/20 border border-blue-400/30 text-blue-300 rounded-full text-xs font-bold mb-2">
            <Sparkles className="w-3.5 h-3.5" /> Identifikasi Berkas & Dus 1 Detik
          </div>
          <h2 className="text-xl font-bold">Pindai / Cari QR Code Pertelaan Arsip</h2>
          <p className="text-xs text-slate-300">Masukkan kode QR dari label boks atau scanner fisik untuk menampilkan dokumen instan.</p>
        </div>

        <button
          onClick={onClose}
          className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-xl text-xs font-bold cursor-pointer shrink-0"
        >
          Kembali ke Dashboard
        </button>
      </div>

      {/* Main Scanner Box */}
      <div className="bg-white p-6 rounded-2xl border border-slate-200/90 shadow-2xs space-y-6 max-w-2xl mx-auto text-center">
        
        <div className="p-8 border-2 border-dashed border-blue-300 bg-blue-50/50 rounded-2xl space-y-4">
          <div className="p-4 bg-blue-600 text-white rounded-full w-fit mx-auto shadow-md animate-pulse">
            <QrCode className="w-8 h-8" />
          </div>

          <div>
            <h3 className="font-bold text-slate-900 text-base">Simulator Pindaian QR Code</h3>
            <p className="text-xs text-slate-500 max-w-md mx-auto">
              Arahkan scanner genggam ke label atau tempel teks data QR Code / Nomor SK / ID Arsip di bawah ini:
            </p>
          </div>

          <div className="flex items-center gap-2 max-w-md mx-auto">
            <input
              type="text"
              value={scanInput}
              onChange={(e) => {
                setScanInput(e.target.value);
                if (e.target.value.length >= 3) {
                  handleProcessScan(e.target.value);
                }
              }}
              placeholder="e.g. arsip-2026-001 ATAU 188.4/01/SK/2026..."
              className="w-full px-4 py-2.5 bg-white border border-slate-300 rounded-xl text-xs font-mono focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
            <button
              onClick={() => handleProcessScan(scanInput)}
              className="px-4 py-2.5 bg-blue-600 hover:bg-blue-500 text-white font-bold rounded-xl text-xs cursor-pointer shadow-xs shrink-0"
            >
              Cari
            </button>
          </div>

          {/* Quick Demo Buttons */}
          <div className="pt-2 flex items-center justify-center gap-2 flex-wrap">
            <span className="text-[11px] font-bold text-slate-400">Contoh Cepat:</span>
            {items.slice(0, 3).map((item) => (
              <button
                key={item.id}
                onClick={() => {
                  setScanInput(item.nomorKeputusan);
                  handleProcessScan(item.nomorKeputusan);
                }}
                className="px-2.5 py-1 bg-white hover:bg-slate-100 border border-slate-200 rounded-lg text-[10px] font-mono text-blue-700 cursor-pointer"
              >
                {item.nomorKeputusan}
              </button>
            ))}
          </div>
        </div>

        {/* Scan Result Card */}
        {hasSearched && (
          <div className="text-left animate-in fade-in duration-200">
            {matchedItem ? (
              <div className="p-5 bg-emerald-50 border-2 border-emerald-500 rounded-2xl space-y-3 shadow-2xs">
                <div className="flex items-center justify-between">
                  <span className="inline-flex items-center gap-1.5 font-bold text-emerald-800 text-xs">
                    <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                    DOKUMEN DITEMUKAN DENGAN SUKSES
                  </span>
                  <span className="font-mono text-amber-900 bg-amber-100 px-2 py-0.5 rounded font-bold text-xs">
                    {matchedItem.noDus}
                  </span>
                </div>

                <div className="space-y-1">
                  <h4 className="font-bold text-slate-900 text-sm">{matchedItem.nomorKeputusan}</h4>
                  <p className="text-xs text-slate-700">{matchedItem.perihal}</p>
                </div>

                <div className="flex items-center gap-4 text-xs text-slate-600 pt-1">
                  <span className="flex items-center gap-1">
                    <MapPin className="w-3.5 h-3.5 text-emerald-600" />
                    {matchedItem.lokasiPenyimpanan}
                  </span>
                  <span>• Tanggal: {matchedItem.tanggal}</span>
                </div>

                <button
                  onClick={() => onSelectFoundItem(matchedItem)}
                  className="w-full py-2.5 bg-emerald-600 hover:bg-emerald-500 text-white font-bold rounded-xl text-xs flex items-center justify-center gap-1.5 cursor-pointer shadow-xs transition-all"
                >
                  <span>Buka Informasi Lengkap Dokumen Ini</span>
                  <ArrowRight className="w-4 h-4" />
                </button>
              </div>
            ) : (
              <div className="p-5 bg-rose-50 border border-rose-200 rounded-2xl text-center space-y-2">
                <AlertCircle className="w-6 h-6 text-rose-500 mx-auto" />
                <h4 className="font-bold text-rose-900 text-xs">Dokumen Tidak Ditemukan</h4>
                <p className="text-[11px] text-rose-700">Kode QR atau kata kunci tidak cocok dengan database pertelaan arsip manapun.</p>
              </div>
            )}
          </div>
        )}

      </div>

    </div>
  );
};
